### ISSUE TITLE
Website 404 uses COGDev links

### ISSUE THREAD

**Issue by Xeovis** [cogdevs/Engine-Bot#3]
The [404 page](https://github.com/cogdevs/Engine-Bot/blob/site/404.html) links to, and uses outdated resources, which instead links to to COGDev resources.

- The 404 page uses COGDev's stylesheet (css/master)
- The "Go home" button sends the user to [cogdevs.github.io](https://cogdevs.github.io/)

**Comment by b-tao** [comment]
Hello, I think I can help with this. How can I start?

**Comment by Xeovis** [comment]
Thanks for offering! You just need to change the paths in the file to things that will not get the things from the main site. Sorry it's simple and for the late response.

**Comment by b-tao** [comment]
Sure I can do that. Can you assign me this issue too? That way I can also push my changes and do a PR

**Comment by Xeovis** [comment]
Sure! Thanks again!

**Comment by b-tao** [comment]
No problem. I made the changes locally, however I get a 'permission denied' when I try push it to the repo. Would it be possible to give me said permissions as well?

**Comment by Xeovis** [comment]
I'm sorry, I'm confused on what you need. Are you trying to make a commit directly to the repo? I don't see why you can't just make a PR?

(Pardon my incompetence, I'm new to this)

**Comment by b-tao** [comment]
Apologies, I was mistaken. I created a PR to this. Let me know if there are any issues.

**Comment by Xeovis** [comment]
I merged it! Thank you for your help 🤗.

(P.S: Sorry for the late response)
